project:
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: "Projects"
      - href: cv.pdf
        text: "CV"
        icon: file-pdf
    right:
      - href: https://www.linkedin.com/in/saumi-rahnamay/
        icon: linkedin


format:
  html:
    theme: cosmo
    css: styles.css



